{"code":"28P01","file":"auth.c","length":107,"level":"error","line":"335","message":"Erro ao conectar ao banco de dados: password authentication failed for user \"avitronuser\"","name":"error","routine":"auth_failed","severity":"FATAL","stack":"error: password authentication failed for user \"avitronuser\"\n    at Parser.parseErrorMessage (/var/www/avitron-site/backend/node_modules/pg-protocol/dist/parser.js:283:98)\n    at Parser.handlePacket (/var/www/avitron-site/backend/node_modules/pg-protocol/dist/parser.js:122:29)\n    at Parser.parse (/var/www/avitron-site/backend/node_modules/pg-protocol/dist/parser.js:35:38)\n    at Socket.<anonymous> (/var/www/avitron-site/backend/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:517:28)\n    at addChunk (node:internal/streams/readable:368:12)\n    at readableAddChunk (node:internal/streams/readable:341:9)\n    at Readable.push (node:internal/streams/readable:278:10)\n    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)","timestamp":"2025-04-07T07:05:40.962Z"}
{"code":"28P01","file":"auth.c","length":107,"level":"error","line":"335","message":"Erro ao conectar ao banco de dados: password authentication failed for user \"avitronuser\"","name":"error","routine":"auth_failed","severity":"FATAL","stack":"error: password authentication failed for user \"avitronuser\"\n    at Parser.parseErrorMessage (/var/www/avitron-site/backend/node_modules/pg-protocol/dist/parser.js:283:98)\n    at Parser.handlePacket (/var/www/avitron-site/backend/node_modules/pg-protocol/dist/parser.js:122:29)\n    at Parser.parse (/var/www/avitron-site/backend/node_modules/pg-protocol/dist/parser.js:35:38)\n    at Socket.<anonymous> (/var/www/avitron-site/backend/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:517:28)\n    at addChunk (node:internal/streams/readable:368:12)\n    at readableAddChunk (node:internal/streams/readable:341:9)\n    at Readable.push (node:internal/streams/readable:278:10)\n    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)","timestamp":"2025-04-07T07:07:24.515Z"}
{"code":"28P01","file":"auth.c","length":107,"level":"error","line":"335","message":"Erro ao conectar ao banco de dados: password authentication failed for user \"avitronuser\"","name":"error","routine":"auth_failed","severity":"FATAL","stack":"error: password authentication failed for user \"avitronuser\"\n    at Parser.parseErrorMessage (/var/www/avitron-site/backend/node_modules/pg-protocol/dist/parser.js:283:98)\n    at Parser.handlePacket (/var/www/avitron-site/backend/node_modules/pg-protocol/dist/parser.js:122:29)\n    at Parser.parse (/var/www/avitron-site/backend/node_modules/pg-protocol/dist/parser.js:35:38)\n    at Socket.<anonymous> (/var/www/avitron-site/backend/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:517:28)\n    at addChunk (node:internal/streams/readable:368:12)\n    at readableAddChunk (node:internal/streams/readable:341:9)\n    at Readable.push (node:internal/streams/readable:278:10)\n    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)","timestamp":"2025-04-07T07:08:42.349Z"}
